# Generated by Django 3.0.4 on 2020-04-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='phone number'),
        ),
    ]
