# Generated by Django 2.2.9 on 2020-05-19 07:47

import StarHorizonElearning.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0003_auto_20200425_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.FileField(default='', storage=StarHorizonElearning.storage_backends.MediaStorage(), upload_to=''),
            preserve_default=False,
        ),
    ]
