# Generated by Django 2.2.9 on 2020-05-19 08:05

import StarHorizonElearning.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0004_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classes',
            field=models.ManyToManyField(blank=True, to='accountManagement.StudentClass'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(storage=StarHorizonElearning.storage_backends.MediaStorage(), upload_to='', verbose_name='Profile picture'),
        ),
    ]
