# Generated by Django 2.2.9 on 2020-11-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0017_user_timeonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timeOnline',
            field=models.DurationField(default=0, verbose_name='timeOnline'),
            preserve_default=False,
        ),
    ]
